// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dX1AA-4cKBygD2v5Ty9F3fI7_8kgMBk',
    appId: '1:531611365448:web:7b1e944b18415cb9afe87d',
    messagingSenderId: '531611365448',
    projectId: 'eagleeye-5f99f',
    authDomain: 'eagleeye-5f99f.firebaseapp.com',
    storageBucket: 'eagleeye-5f99f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0cw2rBh5nOFJ3W7mkq7P5LcaoYP4YWM',
    appId: '1:531611365448:android:0229e7d34193e0daafe87d',
    messagingSenderId: '531611365448',
    projectId: 'eagleeye-5f99f',
    storageBucket: 'eagleeye-5f99f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCsbQfpIkL3q5QnVh5b3u0pkCY-jn0e0',
    appId: '1:531611365448:ios:f1a4614425d6238dafe87d',
    messagingSenderId: '531611365448',
    projectId: 'eagleeye-5f99f',
    storageBucket: 'eagleeye-5f99f.appspot.com',
    iosClientId: '531611365448-ufpu5cmfut2do9cjiv5u44dahk9nqdlp.apps.googleusercontent.com',
    iosBundleId: 'com.knust.eagle-eye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCsbQfpIkL3q5QnVh5b3u0pkCY-jn0e0',
    appId: '1:531611365448:ios:f1a4614425d6238dafe87d',
    messagingSenderId: '531611365448',
    projectId: 'eagleeye-5f99f',
    storageBucket: 'eagleeye-5f99f.appspot.com',
    iosClientId: '531611365448-ufpu5cmfut2do9cjiv5u44dahk9nqdlp.apps.googleusercontent.com',
    iosBundleId: 'com.knust.eagle-eye',
  );
}
